In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv("./CandidateData.csv")

In [4]:
data.head()

,Unnamed: 0,Name,Constituency,Party,Cases,Education,Assets,Liabilities
0,0,Parmar Vijay,RAJKOT,BSP,4,12th Pass,"5,35,000",0
1,1,A M Ariff,ALAPPUZHA,CPI(M),2,Graduate Professional,"1,52,68,906","22,20,700"
2,2,A Narayanaswamy,CHITRADURGA,BJP,0,Graduate,"9,61,97,642",0
3,3,A Natarajan,COIMBATORE,IND,0,5th Pass,"7,000",0
4,4,A Pradeep Kumar,KOZHIKODE,CPI(M),1,12th Pass,"1,19,15,342","20,79,872"

In [5]:
data.info

<bound method DataFrame.info of       Unnamed: 0                             Name       Constituency  \
0              0                     Parmar Vijay             RAJKOT
1              1                        A M Ariff          ALAPPUZHA
2              2                  A Narayanaswamy        CHITRADURGA
3              3                      A Natarajan         COIMBATORE
4              4                  A Pradeep Kumar          KOZHIKODE
5              5                A T Dadakhalandar         DAVANAGERE
6              6            A. Beemarao Milinther            VELLORE
7              7                   A. Christhuraj  BANGALORE CENTRAL
8              8                       A. Devadas            BELLARY
9              9                    A. Habeebulla            VELLORE
10            10                A. Hafeez A. Aziz           BULDHANA
11            11                       A. Hemanth           CHITTOOR
12            12                      A. J. Patel           MAHESANA
13            13                      A. Jayamani          CUDDALORE
14            14                    A. Manikandan          CUDDALORE
15            15                     A. Marimuthu          CUDDALORE
16            16                          A. Raja           NILGIRIS
17            17                  A. Vijaya Kumar            VELLORE
18            18                       A.A. Sabri           CHEVELLA
19            19               A.Antony Sesu Raja          SIVAGANGA
20            20                   A.C. Shanmugam            VELLORE
21            21                      A.G. Mourya      CHENNAI NORTH
22            22                   A.G.Pathimaraj         PUDUCHERRY
23            23                      A.J.Sherine      CHENNAI SOUTH
24            24                     A.K. Moorthy          ARAKKONAM
25            25                     A.Manikandan         TIRUVALLUR
26            26                         A.Naresh      CHENNAI SOUTH
27            27                 A.Radha Krishnan          SIVAGANGA
28            28                           A.Raju    BANGALORE SOUTH
29            29                        A.Sampath           ATTINGAL
...          ...                              ...                ...
4422        4422         Yamanappa Vittal Gunadal            BIJAPUR
4423        4423        Yanamadala Venkata Suresh             GUNTUR
4424        4424       Yarlagadda Rama Mohana Rao      MACHILIPATNAM
4425        4425           Yashwant Rambhau Kasbe           PARBHANI
4426        4426                   Yashwant Singh             NAGINA
4427        4427                   Yasinali Polra           VADODARA
4428        4428                   Yatendra Singh           BAREILLY
4429        4429                     Yedla Suresh           CHEVELLA
4430        4430  Yeduguri Sandinti Avinash Reddy             KADAPA
4431        4431              Yella Rao Siyyadula       VIZIANAGARAM
4432        4432              Yella Venugopal Rao         NARSAPURAM
4433        4433                  Yellala Rajitha          NIZAMABAD
4434        4434                Yeruru Pampapathi            BELLARY
4435        4435                  Yogeesh Nagaraj    BANGALORE SOUTH
4436        4436                     Yogendra Ram         AURANGABAD
4437        4437         Yogendra Viththal Kolate              RAVER
4438        4438                    Yogesh Dahiya         SAHARANPUR
4439        4439                     Yogesh Kadam             RAIGAD
4440        4440                     Yogesh Kumar            KAIRANA
4441        4441                     Yogesh Verma        BULANDSHAHR
4442        4442             Yuvraj Bhimrao Desai           KOLHAPUR
4443        4443           Yuvraj Prakash Bhujbal           BARAMATI
4444        4444                      Zabed Islam             DHUBRI
4445        4445                    Zakir Hussain            NAWGONG
4446        4446         Zala Dalpatsinh Motisinh        SABARKANTHA
4447        4447      Zala Mukeshbhai Bharmalbhai           JUNAGADH
4448        4448       Zala Ramdevsinh Bharatsinh          BHAVNAGAR
4449        4449        Zambad Subhash Manakchand         AURANGABAD
4450        4450               Ziabur Rahman Khan             TEZPUR
4451        4451       Zitruji Chandruji Borutkar             WARDHA

                                      Party  Cases              Education  \
0                                       BSP      4              12th Pass
1                                    CPI(M)      2  Graduate Professional
2                                       BJP      0               Graduate
3                                       IND      0               5th Pass
4                                    CPI(M)      1              12th Pass
5                                       IND      0              10th Pass
6                                       IND      0              10th Pass
7                                       IND      0              10th Pass
8                                   SUCI(C)      0               8th Pass
9        Desiya Uzhavar Uzhaipalar Kazhagam      0               5th Pass
10                                      BSP      0              12th Pass
11                                      IND      0               5th Pass
12                                      INC      0  Graduate Professional
13                                      IND      0  Graduate Professional
14         Purvanchal Janta Party (Secular)      0               8th Pass
15                                      IND      0  Graduate Professional
16                                      DMK      6  Graduate Professional
17                                      IND      0              12th Pass
18                                      IND      0              12th Pass
19                                      IND      0              10th Pass
20                                   AIADMK      0               Graduate
21                      Makkal Needhi Maiam      0          Post Graduate
22                                      BSP      0  Graduate Professional
23                      Naam Tamilar Katchi      0          Post Graduate
24                    Pattali Makkal Katchi      6          Post Graduate
25                                      IND      0              12th Pass
26               Tamil Nadu Ilangyar Katchi      0  Graduate Professional
27                                      IND      0              12th Pass
28                                      BSP      0               Graduate
29                                   CPI(M)      0              Doctorate
...                                     ...    ...                    ...
4422  Republican Party of India (Karnataka)      2               8th Pass
4423                                    IND      0               Graduate
4424                     Bahujan Maha Party      0              12th Pass
4425     Bahujan Republican Socialist Party      0          Post Graduate
4426                                    BJP      0          Post Graduate
4427           New All India Congress Party      0              12th Pass
4428         Bahujan Samyak Party (Mission)      0               Literate
4429                                    IND      0              10th Pass
4430                                  YSRCP      4          Post Graduate
4431                                    IND      0              12th Pass
4432                       Nava Samaj Party      0          Post Graduate
4433                                    IND      0  Graduate Professional
4434                                    IND      0              12th Pass
4435                                    IND      0              12th Pass
4436                                    IND      0               Literate
4437                                    BSP      1              Doctorate
4438                                    AAP      5               Graduate
4439                                    IND      0              12th Pass
4440           Rashtriya Mazdoor Ekta Party      0              12th Pass
4441                                    BSP     28              12th Pass
4442                                    IND      0          Post Graduate
4443                      Jan Adhikar Party      0                 Others
4444                     Asom Gana Parishad      0               Graduate
4445                                    IND      0               Graduate
4446                                    IND      0               8th Pass
4447                                    IND      1              10th Pass
4448              Jan Sangharsh Virat Party      0              12th Pass
4449                                    INC      0              12th Pass
4450                                    IND      2              10th Pass
4451                                    IND      0  Graduate Professional

              Assets   Liabilities
0           5,35,000             0
1        1,52,68,906     22,20,700
2        9,61,97,642             0
3              7,000             0
4        1,19,15,342     20,79,872
5           1,30,139        20,403
6             50,000             0
7           6,91,000      3,75,000
8          19,43,531             0
9           7,75,500             0
10         11,66,769      7,00,000
11            50,000             0
12      69,87,73,712   9,62,20,673
13          9,10,000             0
14          4,91,750      9,20,000
15          3,68,000             0
16       4,95,91,024     14,24,914
17       2,07,50,344             0
18         23,26,979             0
19         17,92,000      8,00,000
20    1,25,84,59,641  36,31,32,594
21       4,15,90,000   1,24,97,000
22          3,97,117      1,79,146
23         34,66,760             0
24       4,60,23,417     77,10,578
25          3,32,400        53,000
26          2,40,000        14,000
27          2,20,000      3,35,000
28       5,44,19,000      4,60,000
29       3,84,48,688     36,11,333
...              ...           ...
4422        3,70,000             0
4423       13,02,000             0
4424     1,00,86,000             0
4425       14,05,000      3,00,000
4426     6,63,52,887      9,00,000
4427       33,63,000     20,14,250
4428     1,95,86,551     11,74,000
4429        1,03,000             0
4430    18,69,69,794   2,28,33,319
4431          57,000             0
4432       10,00,000      2,00,000
4433       19,31,000             0
4434       16,00,000             0
4435     6,10,45,000             0
4436        1,55,000             0
4437       64,40,000     23,00,000
4438    14,95,41,616     11,41,161
4439          36,900             0
4440       31,00,500             0
4441     4,73,37,130     86,09,902
4442       28,35,000     31,00,000
4443        6,17,200             0
4444     1,21,33,685     13,91,293
4445       41,85,000             0
4446       18,27,000             0
4447     1,05,72,716     18,78,780
4448       22,20,000             0
4449    33,94,52,909  19,84,64,347
4450       22,27,138      1,93,616
4451     1,95,28,934     16,00,000

[4452 rows x 8 columns]>

In [6]:
data.describe

<bound method NDFrame.describe of       Unnamed: 0                             Name       Constituency  \
0              0                     Parmar Vijay             RAJKOT
1              1                        A M Ariff          ALAPPUZHA
2              2                  A Narayanaswamy        CHITRADURGA
3              3                      A Natarajan         COIMBATORE
4              4                  A Pradeep Kumar          KOZHIKODE
5              5                A T Dadakhalandar         DAVANAGERE
6              6            A. Beemarao Milinther            VELLORE
7              7                   A. Christhuraj  BANGALORE CENTRAL
8              8                       A. Devadas            BELLARY
9              9                    A. Habeebulla            VELLORE
10            10                A. Hafeez A. Aziz           BULDHANA
11            11                       A. Hemanth           CHITTOOR
12            12                      A. J. Patel           MAHESANA
13            13                      A. Jayamani          CUDDALORE
14            14                    A. Manikandan          CUDDALORE
15            15                     A. Marimuthu          CUDDALORE
16            16                          A. Raja           NILGIRIS
17            17                  A. Vijaya Kumar            VELLORE
18            18                       A.A. Sabri           CHEVELLA
19            19               A.Antony Sesu Raja          SIVAGANGA
20            20                   A.C. Shanmugam            VELLORE
21            21                      A.G. Mourya      CHENNAI NORTH
22            22                   A.G.Pathimaraj         PUDUCHERRY
23            23                      A.J.Sherine      CHENNAI SOUTH
24            24                     A.K. Moorthy          ARAKKONAM
25            25                     A.Manikandan         TIRUVALLUR
26            26                         A.Naresh      CHENNAI SOUTH
27            27                 A.Radha Krishnan          SIVAGANGA
28            28                           A.Raju    BANGALORE SOUTH
29            29                        A.Sampath           ATTINGAL
...          ...                              ...                ...
4422        4422         Yamanappa Vittal Gunadal            BIJAPUR
4423        4423        Yanamadala Venkata Suresh             GUNTUR
4424        4424       Yarlagadda Rama Mohana Rao      MACHILIPATNAM
4425        4425           Yashwant Rambhau Kasbe           PARBHANI
4426        4426                   Yashwant Singh             NAGINA
4427        4427                   Yasinali Polra           VADODARA
4428        4428                   Yatendra Singh           BAREILLY
4429        4429                     Yedla Suresh           CHEVELLA
4430        4430  Yeduguri Sandinti Avinash Reddy             KADAPA
4431        4431              Yella Rao Siyyadula       VIZIANAGARAM
4432        4432              Yella Venugopal Rao         NARSAPURAM
4433        4433                  Yellala Rajitha          NIZAMABAD
4434        4434                Yeruru Pampapathi            BELLARY
4435        4435                  Yogeesh Nagaraj    BANGALORE SOUTH
4436        4436                     Yogendra Ram         AURANGABAD
4437        4437         Yogendra Viththal Kolate              RAVER
4438        4438                    Yogesh Dahiya         SAHARANPUR
4439        4439                     Yogesh Kadam             RAIGAD
4440        4440                     Yogesh Kumar            KAIRANA
4441        4441                     Yogesh Verma        BULANDSHAHR
4442        4442             Yuvraj Bhimrao Desai           KOLHAPUR
4443        4443           Yuvraj Prakash Bhujbal           BARAMATI
4444        4444                      Zabed Islam             DHUBRI
4445        4445                    Zakir Hussain            NAWGONG
4446        4446         Zala Dalpatsinh Motisinh        SABARKANTHA
4447        4447      Zala Mukeshbhai Bharmalbhai           JUNAGADH
4448        4448       Zala Ramdevsinh Bharatsinh          BHAVNAGAR
4449        4449        Zambad Subhash Manakchand         AURANGABAD
4450        4450               Ziabur Rahman Khan             TEZPUR
4451        4451       Zitruji Chandruji Borutkar             WARDHA

                                      Party  Cases              Education  \
0                                       BSP      4              12th Pass
1                                    CPI(M)      2  Graduate Professional
2                                       BJP      0               Graduate
3                                       IND      0               5th Pass
4                                    CPI(M)      1              12th Pass
5                                       IND      0              10th Pass
6                                       IND      0              10th Pass
7                                       IND      0              10th Pass
8                                   SUCI(C)      0               8th Pass
9        Desiya Uzhavar Uzhaipalar Kazhagam      0               5th Pass
10                                      BSP      0              12th Pass
11                                      IND      0               5th Pass
12                                      INC      0  Graduate Professional
13                                      IND      0  Graduate Professional
14         Purvanchal Janta Party (Secular)      0               8th Pass
15                                      IND      0  Graduate Professional
16                                      DMK      6  Graduate Professional
17                                      IND      0              12th Pass
18                                      IND      0              12th Pass
19                                      IND      0              10th Pass
20                                   AIADMK      0               Graduate
21                      Makkal Needhi Maiam      0          Post Graduate
22                                      BSP      0  Graduate Professional
23                      Naam Tamilar Katchi      0          Post Graduate
24                    Pattali Makkal Katchi      6          Post Graduate
25                                      IND      0              12th Pass
26               Tamil Nadu Ilangyar Katchi      0  Graduate Professional
27                                      IND      0              12th Pass
28                                      BSP      0               Graduate
29                                   CPI(M)      0              Doctorate
...                                     ...    ...                    ...
4422  Republican Party of India (Karnataka)      2               8th Pass
4423                                    IND      0               Graduate
4424                     Bahujan Maha Party      0              12th Pass
4425     Bahujan Republican Socialist Party      0          Post Graduate
4426                                    BJP      0          Post Graduate
4427           New All India Congress Party      0              12th Pass
4428         Bahujan Samyak Party (Mission)      0               Literate
4429                                    IND      0              10th Pass
4430                                  YSRCP      4          Post Graduate
4431                                    IND      0              12th Pass
4432                       Nava Samaj Party      0          Post Graduate
4433                                    IND      0  Graduate Professional
4434                                    IND      0              12th Pass
4435                                    IND      0              12th Pass
4436                                    IND      0               Literate
4437                                    BSP      1              Doctorate
4438                                    AAP      5               Graduate
4439                                    IND      0              12th Pass
4440           Rashtriya Mazdoor Ekta Party      0              12th Pass
4441                                    BSP     28              12th Pass
4442                                    IND      0          Post Graduate
4443                      Jan Adhikar Party      0                 Others
4444                     Asom Gana Parishad      0               Graduate
4445                                    IND      0               Graduate
4446                                    IND      0               8th Pass
4447                                    IND      1              10th Pass
4448              Jan Sangharsh Virat Party      0              12th Pass
4449                                    INC      0              12th Pass
4450                                    IND      2              10th Pass
4451                                    IND      0  Graduate Professional

              Assets   Liabilities
0           5,35,000             0
1        1,52,68,906     22,20,700
2        9,61,97,642             0
3              7,000             0
4        1,19,15,342     20,79,872
5           1,30,139        20,403
6             50,000             0
7           6,91,000      3,75,000
8          19,43,531             0
9           7,75,500             0
10         11,66,769      7,00,000
11            50,000             0
12      69,87,73,712   9,62,20,673
13          9,10,000             0
14          4,91,750      9,20,000
15          3,68,000             0
16       4,95,91,024     14,24,914
17       2,07,50,344             0
18         23,26,979             0
19         17,92,000      8,00,000
20    1,25,84,59,641  36,31,32,594
21       4,15,90,000   1,24,97,000
22          3,97,117      1,79,146
23         34,66,760             0
24       4,60,23,417     77,10,578
25          3,32,400        53,000
26          2,40,000        14,000
27          2,20,000      3,35,000
28       5,44,19,000      4,60,000
29       3,84,48,688     36,11,333
...              ...           ...
4422        3,70,000             0
4423       13,02,000             0
4424     1,00,86,000             0
4425       14,05,000      3,00,000
4426     6,63,52,887      9,00,000
4427       33,63,000     20,14,250
4428     1,95,86,551     11,74,000
4429        1,03,000             0
4430    18,69,69,794   2,28,33,319
4431          57,000             0
4432       10,00,000      2,00,000
4433       19,31,000             0
4434       16,00,000             0
4435     6,10,45,000             0
4436        1,55,000             0
4437       64,40,000     23,00,000
4438    14,95,41,616     11,41,161
4439          36,900             0
4440       31,00,500             0
4441     4,73,37,130     86,09,902
4442       28,35,000     31,00,000
4443        6,17,200             0
4444     1,21,33,685     13,91,293
4445       41,85,000             0
4446       18,27,000             0
4447     1,05,72,716     18,78,780
4448       22,20,000             0
4449    33,94,52,909  19,84,64,347
4450       22,27,138      1,93,616
4451     1,95,28,934     16,00,000

[4452 rows x 8 columns]>

In [10]:
type(data['Cases'])

pandas.core.series.Series

In [29]:
data.sort_values(by=['Cases'], ascending=False)

,Unnamed: 0,Name,Constituency,Party,Cases,Education,Assets,Liabilities
1605,1605,K Surendran,PATHANAMTHITTA,BJP,240,Graduate,"40,44,300","13,08,799"
879,879,Dean Kuriakose,IDUKKI,INC,204,Post Graduate,"1,33,95,011","1,00,00,000"
531,531,Bapu Rao Soyam,ADILABAD,BJP,52,12th Pass,"30,99,414","2,31,450"
310,310,Anumula Revanth Reddy,MALKAJGIRI,INC,42,Graduate,"24,53,57,182","2,78,07,304"
1258,1258,George Tirkey,SUNDARGARH,INC,41,12th Pass,"9,01,058",0
3837,3837,Sobha Surendran,ATTINGAL,BJP,40,Graduate,"19,81,638",0
3093,3093,Rajesh Ranjan,MADHEPURA,Jan Adhikar Party (Loktantrik),31,Graduate,"11,95,43,561","1,76,95,194"
1740,1740,Karia Dhirenbhai Amrutlal,JUNAGADH,IND,28,10th Pass,"8,29,28,865","57,96,716"
4441,4441,Yogesh Verma,BULANDSHAHR,BSP,28,12th Pass,"4,73,37,130","86,09,902"
114,114,Adv.Prakash Babu,KOZHIKODE,BJP,22,Post Graduate,"35,24,377","3,43,064"
449,449,B.B.Patil,ZAHIRABAD,TRS,18,Graduate,"1,28,78,51,556","1,15,35,000"
3039,3039,Rajan Ramchandra Kshirsagar,PARBHANI,CPI,15,Graduate,"58,54,206","9,90,000"
3739,3739,Shetty Raju Anna,HATKANANGLE,Swabhimani Paksha,15,10th Pass,"2,44,21,392","7,74,059"
1136,1136,"Eswaran, R",DINDIGUL,IND,14,Graduate,"29,00,000",0
1820,1820,Komatireddy Venakat Reddy,BHONGIR,INC,14,12th Pass,"16,25,43,845","2,40,69,129"
3872,3872,Srinivas Duvvada,SRIKAKULAM,YSRCP,13,Post Graduate,"5,28,21,196","2,58,48,939"
253,253,Anbumani Ramadoss,DHARMAPURI,Pattali Makkal Katchi,12,Graduate Professional,"33,85,35,112","7,26,81,681"
3863,3863,Sri Nisith Pramanik,COOCH BEHAR,BJP,11,8th Pass,"96,29,810",0
1410,1410,Humayun Kabir,MURSHIDABAD,BJP,10,12th Pass,"3,63,08,374","49,00,000"
1536,1536,Jayarajan.P,VADAKARA,CPI(M),10,10th Pass,"90,72,440","6,20,213"
1117,1117,"Elangovan, E.V.K.S.",THENI,INC,10,Graduate,"23,62,41,267","74,50,651"
1850,1850,Krishnakumar C,PALAKKAD,BJP,10,Graduate,"1,12,98,644","14,48,919"
3527,3527,Sanjiv Baban Bhor,AHMEDNAGAR,IND,10,Others,"1,08,11,146","32,22,409"
751,751,Chaudhary Basheer,FIROZABAD,IND,10,8th Pass,"2,75,48,145","16,54,024"
2839,2839,Pradeep Kumar Majhi,NABARANGPUR,INC,10,Graduate,"23,47,000",0
1969,1969,M B Rajesh,PALAKKAD,CPI(M),10,Post Graduate,"1,67,62,314","6,51,136"
2271,2271,Mohammad Azam Khan,RAMPUR,SP,10,Graduate Professional,"4,61,24,814",0
2614,2614,P K Sreemathi,KANNUR,CPI(M),10,12th Pass,"2,45,90,760",0
3894,3894,Subhash Barman,MALDAHA UTTAR,Kamatapur Peoples Party (United),9,5th Pass,"98,11,045",0
894,894,Dengada Pravinbhai,RAJKOT,IND,9,Illiterate,"13,82,000",0
...,...,...,...,...,...,...,...,...
1633,1633,K.Arunachalam,PUDUCHERRY,Agila India Makkal Kazhagam,0,8th Pass,"63,000",0
1667,1667,Kailash Kumar Mishra,BADAUN,AIFB,0,Graduate,"52,34,088","22,000"
1634,1634,K.C. Prakash,UDUPI CHIKMAGALUR,IND,0,10th Pass,"32,90,000",0
1635,1635,K.C.Nagabhushana Reddy,BANGALORE SOUTH,IND,0,Graduate Professional,"16,03,47,647","1,67,27,517"
1636,1636,K.C.Vinay Rajavath,SHIMOGA,IND,0,Graduate,"18,55,573","6,00,000"
1637,1637,K.Chandrasekar,TIRUVALLUR,IND,0,Graduate Professional,"8,44,000",0
1638,1638,K.Chellakkannu,SIVAGANGA,IND,0,10th Pass,"1,30,000",0
1639,1639,K.G. Kutty Deenadayalan,VELLORE,IND,0,Graduate,"92,87,885","14,00,000"
1640,1640,K.G.Mohanan,ATTINGAL,IND,0,10th Pass,"1,00,000",0
1642,1642,K.Jayaraman,CHENNAI SOUTH,IND,0,12th Pass,"1,49,25,696","20,53,100"
1643,1643,K.Kamalanathan,TIRUVALLUR,IND,0,Not Given,"53,02,800",0
1644,1644,K.Kannan,CHENNAI SOUTH,IND,0,Graduate,"2,49,500",0
1645,1645,K.Kuppan,KRISHNAGIRI,IND,0,8th Pass,"26,55,000","2,00,000"
1646,1646,K.L. Arya,ALMORA,UKD,0,Literate,"37,48,627",0
1647,1647,K.Murali Krishnan,CHENNAI SOUTH,Pyramid Party of India,0,Graduate,"4,82,90,000",0
1650,1650,K.P.Munusamy,KRISHNAGIRI,AIADMK,0,Graduate Professional,"11,56,19,769",0
1651,1651,K.Rajashekar Basavaraj Hitnal,KOPPAL,INC,0,12th Pass,"8,49,22,164","3,84,12,374"
1652,1652,K.S. Munirathnam,TIRUPATI,IND,0,Others,"58,92,600",0
1653,1653,K.S.Somasunder,MYSORE,IND,0,Graduate,"6,30,400","2,00,000"
1654,1654,K.Saravana Perumal,CHENNAI SOUTH,IND,0,Graduate,"2,49,000",0
1655,1655,K.Sudhakar,CHENNAI SOUTH,IND,0,5th Pass,"81,000",0
1656,1656,K.Sudhakaran,VADAKARA,CPI(ML) Red Star,0,Graduate Professional,"11,00,158",0
1659,1659,Kabrabam Dhirendra Singha,TRIPURA WEST,IND,0,Post Graduate,"6,587",0
1660,1660,Kachchhi Daudbhai Nathabhai,JAMNAGAR,IND,0,5th Pass,"2,39,000",0
1661,1661,Kachhadiya Naranbhai Bhikhabhai,AMRELI,BJP,0,12th Pass,"3,59,00,763","8,28,961"
1662,1662,Kadam Shrirang Uttomrao,NANDED,IND,0,10th Pass,"22,41,500",0
1663,1663,Kadavala Samatbha,PORBANDAR,BSP,0,8th Pass,"3,00,000","3,58,662"
1664,1664,Kadri Mohammad Sabir,AHMEDABAD EAST,Ambedkar National Congress,0,5th Pass,"50,000",0
1666,1666,Kaif Raza Khan,PILIBHIT,IND,0,Graduate,"30,000",0
4451,4451,Zitruji Chandruji Borutkar,WARDHA,IND,0,Graduate Professional,"1,95,28,934","16,00,000"