In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("./CandidateData.csv")

In [3]:
data.head()

,Name,Constituency,Party,Cases,Education,Assets,Liabilities
0,Parmar Vijay,RAJKOT,BSP,4,12th Pass,"5,35,000",0
1,A M Ariff,ALAPPUZHA,CPI(M),2,Graduate Professional,"1,52,68,906","22,20,700"
2,A Narayanaswamy,CHITRADURGA,BJP,0,Graduate,"9,61,97,642",0
3,A Natarajan,COIMBATORE,IND,0,5th Pass,"7,000",0
4,A Pradeep Kumar,KOZHIKODE,CPI(M),1,12th Pass,"1,19,15,342","20,79,872"

In [4]:
data.info

<bound method DataFrame.info of                                  Name       Constituency  \
0                        Parmar Vijay             RAJKOT
1                           A M Ariff          ALAPPUZHA
2                     A Narayanaswamy        CHITRADURGA
3                         A Natarajan         COIMBATORE
4                     A Pradeep Kumar          KOZHIKODE
5                   A T Dadakhalandar         DAVANAGERE
6               A. Beemarao Milinther            VELLORE
7                      A. Christhuraj  BANGALORE CENTRAL
8                          A. Devadas            BELLARY
9                       A. Habeebulla            VELLORE
10                  A. Hafeez A. Aziz           BULDHANA
11                         A. Hemanth           CHITTOOR
12                        A. J. Patel           MAHESANA
13                        A. Jayamani          CUDDALORE
14                      A. Manikandan          CUDDALORE
15                       A. Marimuthu          CUDDALORE
16                            A. Raja           NILGIRIS
17                    A. Vijaya Kumar            VELLORE
18                         A.A. Sabri           CHEVELLA
19                 A.Antony Sesu Raja          SIVAGANGA
20                     A.C. Shanmugam            VELLORE
21                        A.G. Mourya      CHENNAI NORTH
22                     A.G.Pathimaraj         PUDUCHERRY
23                        A.J.Sherine      CHENNAI SOUTH
24                       A.K. Moorthy          ARAKKONAM
25                       A.Manikandan         TIRUVALLUR
26                           A.Naresh      CHENNAI SOUTH
27                   A.Radha Krishnan          SIVAGANGA
28                             A.Raju    BANGALORE SOUTH
29                          A.Sampath           ATTINGAL
...                               ...                ...
4422         Yamanappa Vittal Gunadal            BIJAPUR
4423        Yanamadala Venkata Suresh             GUNTUR
4424       Yarlagadda Rama Mohana Rao      MACHILIPATNAM
4425           Yashwant Rambhau Kasbe           PARBHANI
4426                   Yashwant Singh             NAGINA
4427                   Yasinali Polra           VADODARA
4428                   Yatendra Singh           BAREILLY
4429                     Yedla Suresh           CHEVELLA
4430  Yeduguri Sandinti Avinash Reddy             KADAPA
4431              Yella Rao Siyyadula       VIZIANAGARAM
4432              Yella Venugopal Rao         NARSAPURAM
4433                  Yellala Rajitha          NIZAMABAD
4434                Yeruru Pampapathi            BELLARY
4435                  Yogeesh Nagaraj    BANGALORE SOUTH
4436                     Yogendra Ram         AURANGABAD
4437         Yogendra Viththal Kolate              RAVER
4438                    Yogesh Dahiya         SAHARANPUR
4439                     Yogesh Kadam             RAIGAD
4440                     Yogesh Kumar            KAIRANA
4441                     Yogesh Verma        BULANDSHAHR
4442             Yuvraj Bhimrao Desai           KOLHAPUR
4443           Yuvraj Prakash Bhujbal           BARAMATI
4444                      Zabed Islam             DHUBRI
4445                    Zakir Hussain            NAWGONG
4446         Zala Dalpatsinh Motisinh        SABARKANTHA
4447      Zala Mukeshbhai Bharmalbhai           JUNAGADH
4448       Zala Ramdevsinh Bharatsinh          BHAVNAGAR
4449        Zambad Subhash Manakchand         AURANGABAD
4450               Ziabur Rahman Khan             TEZPUR
4451       Zitruji Chandruji Borutkar             WARDHA

                                      Party  Cases              Education  \
0                                       BSP      4              12th Pass
1                                    CPI(M)      2  Graduate Professional
2                                       BJP      0               Graduate
3                                       IND      0               5th Pass
4                                    CPI(M)      1              12th Pass
5                                       IND      0              10th Pass
6                                       IND      0              10th Pass
7                                       IND      0              10th Pass
8                                   SUCI(C)      0               8th Pass
9        Desiya Uzhavar Uzhaipalar Kazhagam      0               5th Pass
10                                      BSP      0              12th Pass
11                                      IND      0               5th Pass
12                                      INC      0  Graduate Professional
13                                      IND      0  Graduate Professional
14         Purvanchal Janta Party (Secular)      0               8th Pass
15                                      IND      0  Graduate Professional
16                                      DMK      6  Graduate Professional
17                                      IND      0              12th Pass
18                                      IND      0              12th Pass
19                                      IND      0              10th Pass
20                                   AIADMK      0               Graduate
21                      Makkal Needhi Maiam      0          Post Graduate
22                                      BSP      0  Graduate Professional
23                      Naam Tamilar Katchi      0          Post Graduate
24                    Pattali Makkal Katchi      6          Post Graduate
25                                      IND      0              12th Pass
26               Tamil Nadu Ilangyar Katchi      0  Graduate Professional
27                                      IND      0              12th Pass
28                                      BSP      0               Graduate
29                                   CPI(M)      0              Doctorate
...                                     ...    ...                    ...
4422  Republican Party of India (Karnataka)      2               8th Pass
4423                                    IND      0               Graduate
4424                     Bahujan Maha Party      0              12th Pass
4425     Bahujan Republican Socialist Party      0          Post Graduate
4426                                    BJP      0          Post Graduate
4427           New All India Congress Party      0              12th Pass
4428         Bahujan Samyak Party (Mission)      0               Literate
4429                                    IND      0              10th Pass
4430                                  YSRCP      4          Post Graduate
4431                                    IND      0              12th Pass
4432                       Nava Samaj Party      0          Post Graduate
4433                                    IND      0  Graduate Professional
4434                                    IND      0              12th Pass
4435                                    IND      0              12th Pass
4436                                    IND      0               Literate
4437                                    BSP      1              Doctorate
4438                                    AAP      5               Graduate
4439                                    IND      0              12th Pass
4440           Rashtriya Mazdoor Ekta Party      0              12th Pass
4441                                    BSP     28              12th Pass
4442                                    IND      0          Post Graduate
4443                      Jan Adhikar Party      0                 Others
4444                     Asom Gana Parishad      0               Graduate
4445                                    IND      0               Graduate
4446                                    IND      0               8th Pass
4447                                    IND      1              10th Pass
4448              Jan Sangharsh Virat Party      0              12th Pass
4449                                    INC      0              12th Pass
4450                                    IND      2              10th Pass
4451                                    IND      0  Graduate Professional

              Assets   Liabilities
0           5,35,000             0
1        1,52,68,906     22,20,700
2        9,61,97,642             0
3              7,000             0
4        1,19,15,342     20,79,872
5           1,30,139        20,403
6             50,000             0
7           6,91,000      3,75,000
8          19,43,531             0
9           7,75,500             0
10         11,66,769      7,00,000
11            50,000             0
12      69,87,73,712   9,62,20,673
13          9,10,000             0
14          4,91,750      9,20,000
15          3,68,000             0
16       4,95,91,024     14,24,914
17       2,07,50,344             0
18         23,26,979             0
19         17,92,000      8,00,000
20    1,25,84,59,641  36,31,32,594
21       4,15,90,000   1,24,97,000
22          3,97,117      1,79,146
23         34,66,760             0
24       4,60,23,417     77,10,578
25          3,32,400        53,000
26          2,40,000        14,000
27          2,20,000      3,35,000
28       5,44,19,000      4,60,000
29       3,84,48,688     36,11,333
...              ...           ...
4422        3,70,000             0
4423       13,02,000             0
4424     1,00,86,000             0
4425       14,05,000      3,00,000
4426     6,63,52,887      9,00,000
4427       33,63,000     20,14,250
4428     1,95,86,551     11,74,000
4429        1,03,000             0
4430    18,69,69,794   2,28,33,319
4431          57,000             0
4432       10,00,000      2,00,000
4433       19,31,000             0
4434       16,00,000             0
4435     6,10,45,000             0
4436        1,55,000             0
4437       64,40,000     23,00,000
4438    14,95,41,616     11,41,161
4439          36,900             0
4440       31,00,500             0
4441     4,73,37,130     86,09,902
4442       28,35,000     31,00,000
4443        6,17,200             0
4444     1,21,33,685     13,91,293
4445       41,85,000             0
4446       18,27,000             0
4447     1,05,72,716     18,78,780
4448       22,20,000             0
4449    33,94,52,909  19,84,64,347
4450       22,27,138      1,93,616
4451     1,95,28,934     16,00,000

[4452 rows x 7 columns]>

In [5]:
data.describe

<bound method NDFrame.describe of                                  Name       Constituency  \
0                        Parmar Vijay             RAJKOT
1                           A M Ariff          ALAPPUZHA
2                     A Narayanaswamy        CHITRADURGA
3                         A Natarajan         COIMBATORE
4                     A Pradeep Kumar          KOZHIKODE
5                   A T Dadakhalandar         DAVANAGERE
6               A. Beemarao Milinther            VELLORE
7                      A. Christhuraj  BANGALORE CENTRAL
8                          A. Devadas            BELLARY
9                       A. Habeebulla            VELLORE
10                  A. Hafeez A. Aziz           BULDHANA
11                         A. Hemanth           CHITTOOR
12                        A. J. Patel           MAHESANA
13                        A. Jayamani          CUDDALORE
14                      A. Manikandan          CUDDALORE
15                       A. Marimuthu          CUDDALORE
16                            A. Raja           NILGIRIS
17                    A. Vijaya Kumar            VELLORE
18                         A.A. Sabri           CHEVELLA
19                 A.Antony Sesu Raja          SIVAGANGA
20                     A.C. Shanmugam            VELLORE
21                        A.G. Mourya      CHENNAI NORTH
22                     A.G.Pathimaraj         PUDUCHERRY
23                        A.J.Sherine      CHENNAI SOUTH
24                       A.K. Moorthy          ARAKKONAM
25                       A.Manikandan         TIRUVALLUR
26                           A.Naresh      CHENNAI SOUTH
27                   A.Radha Krishnan          SIVAGANGA
28                             A.Raju    BANGALORE SOUTH
29                          A.Sampath           ATTINGAL
...                               ...                ...
4422         Yamanappa Vittal Gunadal            BIJAPUR
4423        Yanamadala Venkata Suresh             GUNTUR
4424       Yarlagadda Rama Mohana Rao      MACHILIPATNAM
4425           Yashwant Rambhau Kasbe           PARBHANI
4426                   Yashwant Singh             NAGINA
4427                   Yasinali Polra           VADODARA
4428                   Yatendra Singh           BAREILLY
4429                     Yedla Suresh           CHEVELLA
4430  Yeduguri Sandinti Avinash Reddy             KADAPA
4431              Yella Rao Siyyadula       VIZIANAGARAM
4432              Yella Venugopal Rao         NARSAPURAM
4433                  Yellala Rajitha          NIZAMABAD
4434                Yeruru Pampapathi            BELLARY
4435                  Yogeesh Nagaraj    BANGALORE SOUTH
4436                     Yogendra Ram         AURANGABAD
4437         Yogendra Viththal Kolate              RAVER
4438                    Yogesh Dahiya         SAHARANPUR
4439                     Yogesh Kadam             RAIGAD
4440                     Yogesh Kumar            KAIRANA
4441                     Yogesh Verma        BULANDSHAHR
4442             Yuvraj Bhimrao Desai           KOLHAPUR
4443           Yuvraj Prakash Bhujbal           BARAMATI
4444                      Zabed Islam             DHUBRI
4445                    Zakir Hussain            NAWGONG
4446         Zala Dalpatsinh Motisinh        SABARKANTHA
4447      Zala Mukeshbhai Bharmalbhai           JUNAGADH
4448       Zala Ramdevsinh Bharatsinh          BHAVNAGAR
4449        Zambad Subhash Manakchand         AURANGABAD
4450               Ziabur Rahman Khan             TEZPUR
4451       Zitruji Chandruji Borutkar             WARDHA

                                      Party  Cases              Education  \
0                                       BSP      4              12th Pass
1                                    CPI(M)      2  Graduate Professional
2                                       BJP      0               Graduate
3                                       IND      0               5th Pass
4                                    CPI(M)      1              12th Pass
5                                       IND      0              10th Pass
6                                       IND      0              10th Pass
7                                       IND      0              10th Pass
8                                   SUCI(C)      0               8th Pass
9        Desiya Uzhavar Uzhaipalar Kazhagam      0               5th Pass
10                                      BSP      0              12th Pass
11                                      IND      0               5th Pass
12                                      INC      0  Graduate Professional
13                                      IND      0  Graduate Professional
14         Purvanchal Janta Party (Secular)      0               8th Pass
15                                      IND      0  Graduate Professional
16                                      DMK      6  Graduate Professional
17                                      IND      0              12th Pass
18                                      IND      0              12th Pass
19                                      IND      0              10th Pass
20                                   AIADMK      0               Graduate
21                      Makkal Needhi Maiam      0          Post Graduate
22                                      BSP      0  Graduate Professional
23                      Naam Tamilar Katchi      0          Post Graduate
24                    Pattali Makkal Katchi      6          Post Graduate
25                                      IND      0              12th Pass
26               Tamil Nadu Ilangyar Katchi      0  Graduate Professional
27                                      IND      0              12th Pass
28                                      BSP      0               Graduate
29                                   CPI(M)      0              Doctorate
...                                     ...    ...                    ...
4422  Republican Party of India (Karnataka)      2               8th Pass
4423                                    IND      0               Graduate
4424                     Bahujan Maha Party      0              12th Pass
4425     Bahujan Republican Socialist Party      0          Post Graduate
4426                                    BJP      0          Post Graduate
4427           New All India Congress Party      0              12th Pass
4428         Bahujan Samyak Party (Mission)      0               Literate
4429                                    IND      0              10th Pass
4430                                  YSRCP      4          Post Graduate
4431                                    IND      0              12th Pass
4432                       Nava Samaj Party      0          Post Graduate
4433                                    IND      0  Graduate Professional
4434                                    IND      0              12th Pass
4435                                    IND      0              12th Pass
4436                                    IND      0               Literate
4437                                    BSP      1              Doctorate
4438                                    AAP      5               Graduate
4439                                    IND      0              12th Pass
4440           Rashtriya Mazdoor Ekta Party      0              12th Pass
4441                                    BSP     28              12th Pass
4442                                    IND      0          Post Graduate
4443                      Jan Adhikar Party      0                 Others
4444                     Asom Gana Parishad      0               Graduate
4445                                    IND      0               Graduate
4446                                    IND      0               8th Pass
4447                                    IND      1              10th Pass
4448              Jan Sangharsh Virat Party      0              12th Pass
4449                                    INC      0              12th Pass
4450                                    IND      2              10th Pass
4451                                    IND      0  Graduate Professional

              Assets   Liabilities
0           5,35,000             0
1        1,52,68,906     22,20,700
2        9,61,97,642             0
3              7,000             0
4        1,19,15,342     20,79,872
5           1,30,139        20,403
6             50,000             0
7           6,91,000      3,75,000
8          19,43,531             0
9           7,75,500             0
10         11,66,769      7,00,000
11            50,000             0
12      69,87,73,712   9,62,20,673
13          9,10,000             0
14          4,91,750      9,20,000
15          3,68,000             0
16       4,95,91,024     14,24,914
17       2,07,50,344             0
18         23,26,979             0
19         17,92,000      8,00,000
20    1,25,84,59,641  36,31,32,594
21       4,15,90,000   1,24,97,000
22          3,97,117      1,79,146
23         34,66,760             0
24       4,60,23,417     77,10,578
25          3,32,400        53,000
26          2,40,000        14,000
27          2,20,000      3,35,000
28       5,44,19,000      4,60,000
29       3,84,48,688     36,11,333
...              ...           ...
4422        3,70,000             0
4423       13,02,000             0
4424     1,00,86,000             0
4425       14,05,000      3,00,000
4426     6,63,52,887      9,00,000
4427       33,63,000     20,14,250
4428     1,95,86,551     11,74,000
4429        1,03,000             0
4430    18,69,69,794   2,28,33,319
4431          57,000             0
4432       10,00,000      2,00,000
4433       19,31,000             0
4434       16,00,000             0
4435     6,10,45,000             0
4436        1,55,000             0
4437       64,40,000     23,00,000
4438    14,95,41,616     11,41,161
4439          36,900             0
4440       31,00,500             0
4441     4,73,37,130     86,09,902
4442       28,35,000     31,00,000
4443        6,17,200             0
4444     1,21,33,685     13,91,293
4445       41,85,000             0
4446       18,27,000             0
4447     1,05,72,716     18,78,780
4448       22,20,000             0
4449    33,94,52,909  19,84,64,347
4450       22,27,138      1,93,616
4451     1,95,28,934     16,00,000

[4452 rows x 7 columns]>

In [6]:
type(data['Cases'])

pandas.core.series.Series

In [7]:
mostCriminalCases = data.sort_values(by=['Cases'], ascending=False).head(10)

In [8]:
mostCriminalCases.to_csv("MostCriminalCases.csv", index=False)

In [9]:
for ix in range(len(data)):
    if(data.iloc[ix]['Cases']==0):
        data.drop([ix])

IndexError: single positional indexer is out-of-bounds

In [65]:
data

,Name,Constituency,Party,Cases,Education,Assets,Liabilities
0,Parmar Vijay,RAJKOT,BSP,4,12th Pass,"5,35,000",0
1,A M Ariff,ALAPPUZHA,CPI(M),2,Graduate Professional,"1,52,68,906","22,20,700"
2,A Narayanaswamy,CHITRADURGA,BJP,0,Graduate,"9,61,97,642",0
3,A Natarajan,COIMBATORE,IND,0,5th Pass,"7,000",0
4,A Pradeep Kumar,KOZHIKODE,CPI(M),1,12th Pass,"1,19,15,342","20,79,872"
5,A T Dadakhalandar,DAVANAGERE,IND,0,10th Pass,"1,30,139","20,403"
6,A. Beemarao Milinther,VELLORE,IND,0,10th Pass,"50,000",0
7,A. Christhuraj,BANGALORE CENTRAL,IND,0,10th Pass,"6,91,000","3,75,000"
8,A. Devadas,BELLARY,SUCI(C),0,8th Pass,"19,43,531",0
9,A. Habeebulla,VELLORE,Desiya Uzhavar Uzhaipalar Kazhagam,0,5th Pass,"7,75,500",0
10,A. Hafeez A. Aziz,BULDHANA,BSP,0,12th Pass,"11,66,769","7,00,000"
11,A. Hemanth,CHITTOOR,IND,0,5th Pass,"50,000",0
12,A. J. Patel,MAHESANA,INC,0,Graduate Professional,"69,87,73,712","9,62,20,673"
13,A. Jayamani,CUDDALORE,IND,0,Graduate Professional,"9,10,000",0
14,A. Manikandan,CUDDALORE,Purvanchal Janta Party (Secular),0,8th Pass,"4,91,750","9,20,000"
15,A. Marimuthu,CUDDALORE,IND,0,Graduate Professional,"3,68,000",0
16,A. Raja,NILGIRIS,DMK,6,Graduate Professional,"4,95,91,024","14,24,914"
17,A. Vijaya Kumar,VELLORE,IND,0,12th Pass,"2,07,50,344",0
18,A.A. Sabri,CHEVELLA,IND,0,12th Pass,"23,26,979",0
19,A.Antony Sesu Raja,SIVAGANGA,IND,0,10th Pass,"17,92,000","8,00,000"
20,A.C. Shanmugam,VELLORE,AIADMK,0,Graduate,"1,25,84,59,641","36,31,32,594"
21,A.G. Mourya,CHENNAI NORTH,Makkal Needhi Maiam,0,Post Graduate,"4,15,90,000","1,24,97,000"
22,A.G.Pathimaraj,PUDUCHERRY,BSP,0,Graduate Professional,"3,97,117","1,79,146"
23,A.J.Sherine,CHENNAI SOUTH,Naam Tamilar Katchi,0,Post Graduate,"34,66,760",0
24,A.K. Moorthy,ARAKKONAM,Pattali Makkal Katchi,6,Post Graduate,"4,60,23,417","77,10,578"
25,A.Manikandan,TIRUVALLUR,IND,0,12th Pass,"3,32,400","53,000"
26,A.Naresh,CHENNAI SOUTH,Tamil Nadu Ilangyar Katchi,0,Graduate Professional,"2,40,000","14,000"
27,A.Radha Krishnan,SIVAGANGA,IND,0,12th Pass,"2,20,000","3,35,000"
28,A.Raju,BANGALORE SOUTH,BSP,0,Graduate,"5,44,19,000","4,60,000"
29,A.Sampath,ATTINGAL,CPI(M),0,Doctorate,"3,84,48,688","36,11,333"
...,...,...,...,...,...,...,...
4422,Yamanappa Vittal Gunadal,BIJAPUR,Republican Party of India (Karnataka),2,8th Pass,"3,70,000",0
4423,Yanamadala Venkata Suresh,GUNTUR,IND,0,Graduate,"13,02,000",0
4424,Yarlagadda Rama Mohana Rao,MACHILIPATNAM,Bahujan Maha Party,0,12th Pass,"1,00,86,000",0
4425,Yashwant Rambhau Kasbe,PARBHANI,Bahujan Republican Socialist Party,0,Post Graduate,"14,05,000","3,00,000"
4426,Yashwant Singh,NAGINA,BJP,0,Post Graduate,"6,63,52,887","9,00,000"
4427,Yasinali Polra,VADODARA,New All India Congress Party,0,12th Pass,"33,63,000","20,14,250"
4428,Yatendra Singh,BAREILLY,Bahujan Samyak Party (Mission),0,Literate,"1,95,86,551","11,74,000"
4429,Yedla Suresh,CHEVELLA,IND,0,10th Pass,"1,03,000",0
4430,Yeduguri Sandinti Avinash Reddy,KADAPA,YSRCP,4,Post Graduate,"18,69,69,794","2,28,33,319"
4431,Yella Rao Siyyadula,VIZIANAGARAM,IND,0,12th Pass,"57,000",0
4432,Yella Venugopal Rao,NARSAPURAM,Nava Samaj Party,0,Post Graduate,"10,00,000","2,00,000"
4433,Yellala Rajitha,NIZAMABAD,IND,0,Graduate Professional,"19,31,000",0
4434,Yeruru Pampapathi,BELLARY,IND,0,12th Pass,"16,00,000",0
4435,Yogeesh Nagaraj,BANGALORE SOUTH,IND,0,12th Pass,"6,10,45,000",0
4436,Yogendra Ram,AURANGABAD,IND,0,Literate,"1,55,000",0
4437,Yogendra Viththal Kolate,RAVER,BSP,1,Doctorate,"64,40,000","23,00,000"
4438,Yogesh Dahiya,SAHARANPUR,AAP,5,Graduate,"14,95,41,616","11,41,161"
4439,Yogesh Kadam,RAIGAD,IND,0,12th Pass,"36,900",0
4440,Yogesh Kumar,KAIRANA,Rashtriya Mazdoor Ekta Party,0,12th Pass,"31,00,500",0
4441,Yogesh Verma,BULANDSHAHR,BSP,28,12th Pass,"4,73,37,130","86,09,902"
4442,Yuvraj Bhimrao Desai,KOLHAPUR,IND,0,Post Graduate,"28,35,000","31,00,000"
4443,Yuvraj Prakash Bhujbal,BARAMATI,Jan Adhikar Party,0,Others,"6,17,200",0
4444,Zabed Islam,DHUBRI,Asom Gana Parishad,0,Graduate,"1,21,33,685","13,91,293"
4445,Zakir Hussain,NAWGONG,IND,0,Graduate,"41,85,000",0
4446,Zala Dalpatsinh Motisinh,SABARKANTHA,IND,0,8th Pass,"18,27,000",0
4447,Zala Mukeshbhai Bharmalbhai,JUNAGADH,IND,1,10th Pass,"1,05,72,716","18,78,780"
4448,Zala Ramdevsinh Bharatsinh,BHAVNAGAR,Jan Sangharsh Virat Party,0,12th Pass,"22,20,000",0
4449,Zambad Subhash Manakchand,AURANGABAD,INC,0,12th Pass,"33,94,52,909","19,84,64,347"
4450,Ziabur Rahman Khan,TEZPUR,IND,2,10th Pass,"22,27,138","1,93,616"
4451,Zitruji Chandruji Borutkar,WARDHA,IND,0,Graduate Professional,"1,95,28,934","16,00,000"